server:
  port: "8000"

db:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

nats:
  cluster_id: "local_cluster"
  client_id: "subscriber"
  port: "4222"
  host: "nats-streaming"